syntax

diff --git a/.github/workflows/rebuild_required.yaml b/.github/workflows/rebuild_required.yaml
--- a/.github/workflows/rebuild_required.yaml
+++ b/.github/workflows/rebuild_required.yaml
@@ -11,10 +11,10 @@ jobs:
       - name: Test egibility to tun
         run: |
           if [[ "${{ secrets.KEYCODE}}x" == ${{ github.event.client_payload.authorization }}x" ]]; then
-          echo "Authorized to proceed."
+            echo "Authorized to proceed."
           else
-          echo "Authorization failed."
-          exit 1
+            echo "Authorization failed."
+            exit 1
           fi
 
       - name: Checkout the change from Machinekit-docs
